import { useEffect, useState } from "react";
import { api, type DeployWorkspaceData, type OverviewPhase } from "./api";

const empty: DeployWorkspaceData = {
  test_report_ready: false,
  profile: { target_environment:"Production", production_url:"", provider:"", deployment_status:"PREPARING", configuration_notes:"", configuration_keys:[], migrations_required:false, migrations_plan:"", backups_required:false, backups_plan:"", monitoring_required:true, monitoring_plan:"", healthcheck_required:true, healthcheck:"", rollback_strategy:"", deployed_version:"", deployed_at:null, release_notes:"" },
  artifacts: [],
};
type Profile = DeployWorkspaceData["profile"];
const preparations = [
  ["migrations_required","migrations_plan","Votre projet doit-il modifier sa base de données ?","Décrivez comment appliquer et vérifier les migrations."],
  ["backups_required","backups_plan","Une sauvegarde doit-elle être créée avant la mise en ligne ?","Expliquez où elle sera conservée et comment la restaurer."],
  ["monitoring_required","monitoring_plan","Souhaitez-vous être alerté si le service rencontre un problème ?","Indiquez les logs, métriques ou alertes prévus."],
  ["healthcheck_required","healthcheck","HORUS doit-il vérifier automatiquement que le service répond ?","Indiquez l’URL ou la vérification de bonne santé."],
] as const;

export function DeployWorkspace({ phase, token, onChanged }:{ phase:OverviewPhase; token:string; onChanged:()=>Promise<void> }) {
  const [data,setData]=useState(empty); const [busy,setBusy]=useState(""); const [error,setError]=useState("");
  const locked=phase.status==="VALIDATED"; const profile=data.profile;
  useEffect(()=>{let cancelled=false;api.deploy(phase.id,token).then(value=>{if(!cancelled)setData(value)}).catch(()=>{if(!cancelled)setError("Impossible de charger la mise en production.")});return()=>{cancelled=true}},[phase.id,token]);
  function change<K extends keyof Profile>(key:K,value:Profile[K]){setData(current=>({...current,profile:{...current.profile,[key]:value}}))}
  async function save(){setBusy("save");setError("");try{setData(await api.saveDeploy(phase.id,profile,token));await onChanged()}catch{setError("Vérifiez les informations de mise en production.")}finally{setBusy("")}}
  async function report(){setBusy("report");setError("");try{await api.generateReleaseReport(phase.id,token);setData(await api.deploy(phase.id,token));await onChanged()}catch{setError("Confirmez chaque préparation requise et le déploiement avant le rapport.")}finally{setBusy("")}}
  return <section className="mt-14 rounded-[2rem] border border-black/10 bg-white/55 p-6 sm:p-8" id="deploy-workspace">
    <p className="text-xs font-semibold uppercase tracking-[.2em] text-[#d9503f]">Phase 06 · Déployer</p><h2 className="mt-3 text-4xl font-semibold">Mettre votre projet en ligne, sereinement.</h2><p className="mt-2 text-sm text-black/50">HORUS vérifie chaque filet de sécurité avant de déclarer le projet livré.</p>
    {!data.test_report_ready&&<p className="mt-5 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Le rapport de test validé est requis.</p>}
    <div className="mt-8 grid gap-5 lg:grid-cols-2">
      <article className="rounded-2xl border border-black/10 p-5"><h3 className="font-semibold">Où la version sera-t-elle accessible ?</h3><p className="mt-1 text-xs text-black/45">Indiquez l’hébergement et l’adresse publique.</p><div className="mt-4 grid gap-2"><input aria-label="Environnement cible" className="rounded-lg border p-2 text-sm" disabled={locked} onChange={e=>change("target_environment",e.target.value)} value={profile.target_environment}/><input aria-label="Fournisseur" className="rounded-lg border p-2 text-sm" disabled={locked} onChange={e=>change("provider",e.target.value)} placeholder="Railway, AWS, serveur interne…" value={profile.provider}/><input aria-label="URL de production" className="rounded-lg border p-2 text-sm" disabled={locked} onChange={e=>change("production_url",e.target.value)} placeholder="https://mon-projet.fr" value={profile.production_url}/><input aria-label="Version déployée" className="rounded-lg border p-2 text-sm" disabled={locked} onChange={e=>change("deployed_version",e.target.value)} placeholder="v1.0.0 ou SHA" value={profile.deployed_version}/><select aria-label="État du déploiement" className="rounded-lg border p-2 text-sm" disabled={locked} onChange={e=>change("deployment_status",e.target.value as Profile["deployment_status"])} value={profile.deployment_status}><option value="PREPARING">En préparation</option><option value="READY">Prêt à déployer</option><option value="DEPLOYED">Déployé</option><option value="FAILED">Échec</option><option value="ROLLED_BACK">Version précédente restaurée</option></select></div></article>
      <article className="rounded-2xl border border-black/10 p-5"><h3 className="font-semibold">De quelles configurations la production a-t-elle besoin ?</h3><p className="mt-1 text-xs text-black/45">Listez uniquement les noms de variables, jamais leurs valeurs secrètes.</p><textarea aria-label="Configuration de production" className="mt-4 min-h-24 w-full rounded-lg border p-2 text-sm" disabled={locked} onChange={e=>change("configuration_notes",e.target.value)} placeholder="Ex. domaine configuré, emails activés…" value={profile.configuration_notes}/><textarea aria-label="Noms des variables" className="mt-2 min-h-20 w-full rounded-lg border p-2 text-sm" disabled={locked} onChange={e=>change("configuration_keys",e.target.value.split("\n").filter(Boolean))} placeholder="DATABASE_URL (nom uniquement)" value={profile.configuration_keys.map(String).join("\n")}/></article>
      {preparations.map(([required,plan,title,help])=><article className="rounded-2xl border border-black/10 p-5" key={required}><h3 className="font-semibold">{title}</h3><p className="mt-1 text-xs text-black/45">{help}</p><div className="mt-4 flex gap-4 text-sm"><label><input checked={!profile[required]} disabled={locked} name={required} onChange={()=>change(required,false)} type="radio"/> Non requis</label><label><input checked={profile[required]} disabled={locked} name={required} onChange={()=>change(required,true)} type="radio"/> Oui, à préparer</label></div>{profile[required]&&<textarea aria-label={title} className="mt-3 min-h-20 w-full rounded-lg border p-2 text-sm" disabled={locked} onChange={e=>change(plan,e.target.value)} value={profile[plan] as string}/>}</article>)}
      <article className="rounded-2xl border border-black/10 p-5 lg:col-span-2"><h3 className="font-semibold">Si la nouvelle version rencontre un problème, comment reviendrez-vous à la version précédente ?</h3><p className="mt-1 text-xs text-black/45">Une procédure courte suffit : version précédente, commande ou personne responsable.</p><textarea aria-label="Retour à la version précédente" className="mt-3 min-h-20 w-full rounded-lg border p-2 text-sm" disabled={locked} onChange={e=>change("rollback_strategy",e.target.value)} value={profile.rollback_strategy}/><textarea aria-label="Notes de release" className="mt-2 min-h-20 w-full rounded-lg border p-2 text-sm" disabled={locked} onChange={e=>change("release_notes",e.target.value)} placeholder="Qu’est-ce qui change dans cette version ?" value={profile.release_notes}/></article>
    </div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 flex flex-wrap gap-3"><button className="rounded-full bg-black px-5 py-2 text-sm font-bold text-white disabled:opacity-35" disabled={locked||!!busy} onClick={()=>void save()}>Enregistrer la préparation</button><button className="rounded-full bg-[#d9503f] px-5 py-2 text-sm font-bold text-white disabled:opacity-35" disabled={locked||!!busy} onClick={()=>void report()}>{data.artifacts.includes("REPORT")?"✓ Régénérer le rapport":"Générer RELEASE_REPORT"}</button><button className="rounded-full border border-black px-5 py-2 text-sm font-bold disabled:opacity-35" disabled={locked||!!busy||!data.artifacts.includes("REPORT")} onClick={()=>void api.validatePhase(phase.id,token,"Projet livré").then(onChanged).catch(()=>setError("Le rapport de release doit être prêt."))}>{locked?"HORUS Method = 100 % — projet livré":"Valider et terminer HORUS →"}</button></div>
  </section>
}
