import { useEffect,useState } from "react";
import { api,type DeployWorkspaceData,type OverviewPhase } from "./api";
import { AdvancedSection,GuidedQuestion,NextAction } from "./GuidedUx";
const empty:DeployWorkspaceData={test_report_ready:false,profile:{target_environment:"Production",production_url:"",provider:"",deployment_status:"PREPARING",configuration_notes:"",configuration_keys:[],migrations_required:false,migrations_plan:"",backups_required:false,backups_plan:"",monitoring_required:true,monitoring_plan:"",healthcheck_required:true,healthcheck:"",rollback_strategy:"",deployed_version:"",deployed_at:null,release_notes:""},artifacts:[]};
type Profile=DeployWorkspaceData["profile"];
type RequiredKey="migrations_required"|"backups_required"|"monitoring_required"|"healthcheck_required";type PlanKey="migrations_plan"|"backups_plan"|"monitoring_plan"|"healthcheck";
const preparations:[RequiredKey,PlanKey,string,string,string][]=[
 ["migrations_required","migrations_plan","Ton application utilise-t-elle une base de données ?","Si elle change, comment appliquer et vérifier ces changements ?","Décrire les changements à appliquer"],
 ["backups_required","backups_plan","Comment protéger les données en cas de problème ?","Une sauvegarde permet de retrouver les données si la mise en ligne échoue.","Où se trouve la sauvegarde et comment la restaurer ?"],
 ["healthcheck_required","healthcheck","Comment sauras-tu que l’application fonctionne ?","HORUS peut vérifier régulièrement qu’une page ou un service répond.","Adresse ou vérification utilisée"],
 ["monitoring_required","monitoring_plan","Comment sauras-tu qu’un problème apparaît après la mise en ligne ?","Des alertes ou journaux permettent de réagir rapidement.","Alertes, journaux ou personne prévenue"]
];
export function DeployWorkspace({phase,token,onChanged}:{phase:OverviewPhase;token:string;onChanged:()=>Promise<void>}){
 const [data,setData]=useState(empty);const [unknown,setUnknown]=useState<RequiredKey[]>([]);const [busy,setBusy]=useState("");const [error,setError]=useState("");const locked=phase.status==="VALIDATED";const profile=data.profile;
 useEffect(()=>{let stop=false;api.deploy(phase.id,token).then(value=>{if(!stop)setData(value)}).catch(()=>!stop&&setError("Impossible de charger l’assistant de mise en ligne."));return()=>{stop=true}},[phase.id,token]);
 function change<K extends keyof Profile>(key:K,value:Profile[K]){setData(current=>({...current,profile:{...current.profile,[key]:value}}))}
 function choice(required:RequiredKey,value:"YES"|"NO"|"UNKNOWN"){setUnknown(current=>value==="UNKNOWN"?[...current.filter(x=>x!==required),required]:current.filter(x=>x!==required));change(required,value!=="NO")}
 async function save(){setBusy("save");setError("");try{setData(await api.saveDeploy(phase.id,profile,token));await onChanged()}catch{setError("Vérifie les réponses de mise en ligne puis réessaie.")}finally{setBusy("")}}
 async function report(){setBusy("report");setError("");try{await api.generateReleaseReport(phase.id,token);setData(await api.deploy(phase.id,token));await onChanged()}catch{setError("HORUS ne peut pas encore préparer le bilan : complète les protections, confirme la mise en ligne et indique l’adresse publique.")}finally{setBusy("")}}
 const prepared=preparations.filter(([required,plan])=>!profile[required]||Boolean(String(profile[plan]).trim())).length;const missing=!data.test_report_ready?"Termine d’abord les vérifications du produit.":!profile.provider?"Indique où le produit sera disponible.":!profile.configuration_notes?"Décris la configuration nécessaire, sans valeur secrète.":prepared<preparations.length?"Réponds aux questions de protection et de suivi.":!profile.rollback_strategy?"Explique comment revenir à la version précédente.":profile.deployment_status!=="DEPLOYED"||!profile.production_url||!profile.deployed_version?"Confirme la mise en ligne, son adresse et sa version.":!data.artifacts.includes("REPORT")?"Demande à HORUS de préparer le bilan de mise en ligne.":"Le bilan est prêt : termine HORUS.";
 return <section className="mt-14 rounded-[2rem] border border-black/10 bg-white/55 p-6 sm:p-8" id="deploy-workspace"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#d9503f]">Phase 06 · Mettre en ligne</p><h2 className="mt-3 text-4xl font-semibold">Préparons ton produit pour qu’il puisse être utilisé.</h2><p className="mt-2 text-sm text-black/50">HORUS vérifie les protections essentielles. Aucune valeur secrète ne sera demandée ni stockée.</p>{!data.test_report_ready&&<p className="mt-5 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Les vérifications doivent être validées avant la mise en ligne.</p>}<div className="mt-8 space-y-5">
 <GuidedQuestion complete={!!profile.provider} help="Indique le service ou l’endroit choisi pour accueillir le produit." example="Railway, un serveur d’entreprise ou un hébergeur web." number={1} title="Où sera disponible ton produit ?"><div className="grid gap-3 sm:grid-cols-2"><input aria-label="Lieu d’hébergement" className="rounded-xl border p-3" disabled={locked} onChange={e=>change("provider",e.target.value)} placeholder="Service d’hébergement" value={profile.provider}/><input aria-label="Adresse publique" className="rounded-xl border p-3" disabled={locked} onChange={e=>change("production_url",e.target.value)} placeholder="https://mon-produit.fr" value={profile.production_url}/></div></GuidedQuestion>
 <GuidedQuestion complete={!!profile.configuration_notes} help="Décris ce qui doit être activé ou configuré. Ne saisis jamais un mot de passe, une clé ou une valeur secrète." example="Les emails sont activés et le nom de domaine est relié." number={2} title="De quoi ton produit a-t-il besoin pour fonctionner en ligne ?"><textarea aria-label="Configuration nécessaire" className="w-full rounded-xl border p-3" disabled={locked} onChange={e=>change("configuration_notes",e.target.value)} value={profile.configuration_notes}/><AdvancedSection><p className="mb-2 text-xs">Noms des réglages seulement, jamais leurs valeurs.</p><textarea aria-label="Noms des variables" className="w-full rounded-xl border p-3" disabled={locked} onChange={e=>change("configuration_keys",e.target.value.split("\n").filter(Boolean))} placeholder="DATABASE_URL (nom uniquement)" value={profile.configuration_keys.map(String).join("\n")}/></AdvancedSection></GuidedQuestion>
 {preparations.map(([required,plan,title,help,placeholder],index)=><GuidedQuestion complete={!profile[required]||Boolean(String(profile[plan]).trim())} help={help} key={required} number={index+3} title={title}><div className="flex flex-wrap gap-2">{([['YES','Oui'],['NO','Non requis'],['UNKNOWN','Je ne sais pas encore']] as const).map(([value,label])=><label className="rounded-xl border px-4 py-3 text-sm" key={value}><input checked={value==="UNKNOWN"?unknown.includes(required):value==="YES"?profile[required]&&!unknown.includes(required):!profile[required]} disabled={locked} name={required} onChange={()=>choice(required,value)} type="radio"/> {label}</label>)}</div>{profile[required]&&!unknown.includes(required)&&<textarea aria-label={title} className="mt-3 min-h-20 w-full rounded-xl border p-3" disabled={locked} onChange={e=>change(plan,e.target.value)} placeholder={placeholder} value={String(profile[plan])}/>}</GuidedQuestion>)}
 <GuidedQuestion complete={!!profile.rollback_strategy} help="Une phrase courte suffit : version précédente, action à faire ou personne responsable." number={7} title="Si cette nouvelle version rencontre un problème, comment reviendras-tu à la précédente ?"><textarea aria-label="Retour à la version précédente" className="w-full rounded-xl border p-3" disabled={locked} onChange={e=>change("rollback_strategy",e.target.value)} placeholder="Je réactive la version précédente…" value={profile.rollback_strategy}/></GuidedQuestion>
 <GuidedQuestion complete={profile.deployment_status==="DEPLOYED"&&!!profile.production_url&&!!profile.deployed_version} help="Quand le produit est accessible, indique sa version et confirme son état." number={8} title="Le produit est-il maintenant disponible ?"><div className="grid gap-3 sm:grid-cols-2"><input aria-label="Version mise en ligne" className="rounded-xl border p-3" disabled={locked} onChange={e=>change("deployed_version",e.target.value)} placeholder="Version 1.0" value={profile.deployed_version}/><select aria-label="État de la mise en ligne" className="rounded-xl border p-3" disabled={locked} onChange={e=>change("deployment_status",e.target.value as Profile["deployment_status"])} value={profile.deployment_status}><option value="PREPARING">Je prépare la mise en ligne</option><option value="READY">Tout est prêt</option><option value="DEPLOYED">Le produit est disponible</option><option value="FAILED">La mise en ligne a échoué</option><option value="ROLLED_BACK">La version précédente a été restaurée</option></select><textarea aria-label="Nouveautés de cette version" className="rounded-xl border p-3 sm:col-span-2" disabled={locked} onChange={e=>change("release_notes",e.target.value)} placeholder="Qu’est-ce qui change dans cette version ?" value={profile.release_notes}/></div></GuidedQuestion>
 </div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 flex flex-wrap gap-3"><button className="rounded-full bg-black px-5 py-3 text-sm font-bold text-white disabled:opacity-35" disabled={locked||!!busy} onClick={()=>void save()} type="button">Enregistrer mes réponses</button><button className="rounded-full bg-[#d9503f] px-5 py-3 text-sm font-bold text-white disabled:opacity-35" disabled={locked||!!busy} onClick={()=>void report()} type="button">{data.artifacts.includes("REPORT")?"✓ Mettre à jour le bilan":"Préparer le bilan de mise en ligne"}</button><button className="rounded-full border border-black px-5 py-3 text-sm font-bold disabled:opacity-35" disabled={locked||!!busy||!data.artifacts.includes("REPORT")} onClick={()=>void api.validatePhase(phase.id,token,"Projet livré").then(onChanged).catch(()=>setError("Le bilan doit refléter la mise en ligne actuelle."))} type="button">{locked?"HORUS = 100 % — projet livré":"Terminer HORUS →"}</button></div><div className="mt-5"><NextAction>{missing}</NextAction></div></section>;
}
