import { useEffect, useState } from "react";
import { api, type DesignComponent, type DesignWorkspaceData, type OverviewPhase } from "./api";
import { AdvancedSection, GuidedQuestion, NextAction, Suggestions } from "./GuidedUx";

const empty: DesignWorkspaceData = { components: [], connections: [], ux_flows: [], features: [], api_contracts: [], security_controls: [], decisions: [], artifacts: [] };
const technicalArtifacts = ["ARCHITECTURE","UX","FEATURES","API_CONTRACTS","SECURITY","ADR_INDEX","DESIGN_PACK"];
const accepted = (items: unknown[]) => items.some((item) => typeof item === "object" && item !== null && "status" in item && item.status === "ACCEPTED");
const text = (item: unknown, key: string) => typeof item === "object" && item !== null && key in item ? String((item as Record<string,unknown>)[key]) : "";

export function DesignWorkspace({phase,token,onChanged}:{phase:OverviewPhase;token:string;onChanged:()=>Promise<void>}) {
  const [data,setData]=useState(empty); const [actions,setActions]=useState<string[]>([]); const [platforms,setPlatforms]=useState<string[]>([]); const [integrations,setIntegrations]=useState<string[]>([]); const [entry,setEntry]=useState(""); const [busy,setBusy]=useState(""); const [error,setError]=useState("");
  const locked=phase.status==="VALIDATED";
  useEffect(()=>{let stop=false;api.design(phase.id,token).then(value=>{if(!stop)setData(value)}).catch(()=>!stop&&setError("Impossible de charger cette étape."));return()=>{stop=true}},[phase.id,token]);
  const steps=[data.ux_flows.length>0,data.components.length>0,data.connections.length>0,data.security_controls.length>0,data.artifacts.includes("DESIGN_PACK")]; const done=steps.filter(Boolean).length;
  const addDoc=(key:"ux_flows"|"features"|"security_controls",title:string)=>setData(value=>({...value,[key]:[...value[key],{title,description:title}]}));
  function prepareProposal(){const selected=platforms.length?platforms:["Site web"];const components:DesignComponent[]=selected.map((platform,index)=>({name:`Interface ${index+1}`,category:"FRONTEND",responsibility:`Permettre l’utilisation sur ${platform.toLowerCase()}`,technology:platform}));components.push({name:"Service du produit",category:"BACKEND",responsibility:"Appliquer les règles du produit",technology:"API sécurisée"});setData(value=>({...value,components,connections:integrations.filter(x=>x!=="Aucune intégration").map(service=>({source_name:"Service du produit",target_name:service,protocol:"HTTPS",description:`Échange avec ${service}`})),api_contracts:[{title:"Échanges du produit",description:"Contrat généré depuis les usages décrits"}],decisions:[{title:"Proposition HORUS",description:"Choix générés depuis les réponses",status:"ACCEPTED"}]}));}
  async function save(){setBusy("save");setError("");try{setData(await api.saveDesign(phase.id,data,token));await onChanged()}catch{setError("Ajoute au moins une réponse dans chaque partie avant d’enregistrer.")}finally{setBusy("")}}
  async function artifact(kind:string){setBusy(kind);setError("");try{await api.generateDesignArtifact(phase.id,kind,token);setData(await api.design(phase.id,token));await onChanged()}catch{setError("HORUS a besoin des usages, fonctionnalités, besoins particuliers et choix proposés avant de préparer ce document.")}finally{setBusy("")}}
  async function validate(){setBusy("validate");try{await api.validatePhase(phase.id,token,"Conception guidée terminée");await onChanged()}catch{setError("Prépare d’abord le dossier complet avec HORUS.")}finally{setBusy("")}}
  return <section className="mt-14 rounded-[2rem] border border-black/10 bg-white/55 p-6 sm:p-8" id="design-workspace"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#d9503f]">Phase 03 · Imaginer le fonctionnement</p><h2 className="mt-3 text-4xl font-semibold">Comment ton produit prendra-t-il vie ?</h2><p className="mt-2 text-sm text-black/50">Décris les usages avec tes mots. HORUS proposera les choix techniques.</p><div className="mt-5 flex items-center gap-3"><div className="h-2 flex-1 rounded-full bg-black/10"><div className="h-full rounded-full bg-[#d9503f]" style={{width:`${done/steps.length*100}%`}}/></div><span className="text-sm font-semibold">{done}/{steps.length}</span></div><div className="mt-8 space-y-5">
    <GuidedQuestion complete={data.ux_flows.length>0} help="Choisis les actions principales, puis ajoute celles qui sont propres à ton idée." example="Une personne crée un compte, puis crée et partage un projet." number={1} title="Comment les utilisateurs vont-ils utiliser ton produit ?"><Suggestions onToggle={choice=>{setActions(current=>current.includes(choice)?current.filter(x=>x!==choice):[...current,choice]);addDoc("ux_flows",choice)}} options={["Créer un compte","Se connecter","Créer quelque chose","Consulter","Modifier","Partager","Payer","Autre"]} selected={actions}/><div className="mt-3 flex gap-2"><input aria-label="Autre action utilisateur" className="flex-1 rounded-xl border p-3" disabled={locked} onChange={e=>setEntry(e.target.value)} placeholder="Une autre action…" value={entry}/><button disabled={locked||!entry.trim()} onClick={()=>{addDoc("ux_flows",entry);setEntry("")}} type="button">Ajouter</button></div></GuidedQuestion>
    <GuidedQuestion complete={data.components.length>0} help="Cela permet à HORUS de proposer une organisation adaptée." number={2} title="Où ton produit sera-t-il utilisé ?"><Suggestions onToggle={choice=>setPlatforms(current=>current.includes(choice)?current.filter(x=>x!==choice):[...current,choice])} options={["Site web","Application mobile","Ordinateur","API","Plusieurs plateformes","Je ne sais pas encore"]} selected={platforms}/></GuidedQuestion>
    <GuidedQuestion complete={data.connections.length>0||integrations.includes("Aucune intégration")} help="Sélectionne seulement ce qui est utile. Tu peux indiquer qu’aucune connexion n’est nécessaire." number={3} title="Ton produit doit-il communiquer avec d’autres services ?"><Suggestions onToggle={choice=>setIntegrations(current=>current.includes(choice)?current.filter(x=>x!==choice):[...current,choice])} options={["Paiement","Email","Stockage","Google","GitHub","Aucune intégration"]} selected={integrations}/></GuidedQuestion>
    <GuidedQuestion complete={data.security_controls.length>0} help="Explique ce qui compte pour tes utilisateurs, sans chercher le terme technique." example="Les informations personnelles ne doivent être visibles que par leur propriétaire." number={4} title="Y a-t-il des besoins particuliers ?"><Suggestions onToggle={choice=>addDoc("security_controls",choice)} options={["Protéger les données","Répondre rapidement","Rester disponible","Respecter la confidentialité","Être accessible"]} selected={data.security_controls.map(item=>text(item,"title"))}/><button className="mt-4 rounded-full bg-black px-5 py-3 text-sm font-bold text-white" disabled={locked} onClick={()=>{if(data.ux_flows.length===0) addDoc("ux_flows","Utiliser le produit");if(data.features.length===0) addDoc("features","Première version utilisable");if(data.security_controls.length===0) addDoc("security_controls","Accès protégé");prepareProposal()}} type="button">Préparer les choix avec HORUS</button></GuidedQuestion>
    <AdvancedSection><p className="text-sm text-black/55">Proposition générée : {data.components.map(item=>item.name).join(", ")||"à préparer"}. Les décisions d’architecture et connexions restent modifiables via l’API existante.</p><div className="mt-4 flex flex-wrap gap-2">{technicalArtifacts.map(kind=><button className={`rounded-full border px-4 py-2 text-xs ${data.artifacts.includes(kind)?"bg-black text-white":""}`} disabled={locked||!!busy||((kind==="ADR_INDEX"||kind==="DESIGN_PACK")&&!accepted(data.decisions))} key={kind} onClick={()=>void artifact(kind)} type="button">{data.artifacts.includes(kind)?"✓ ":""}{kind}</button>)}</div></AdvancedSection>
  </div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 flex flex-wrap gap-3"><button className="rounded-full bg-black px-5 py-3 text-sm font-bold text-white" disabled={locked||!!busy} onClick={()=>void save()} type="button">Enregistrer mes réponses</button><button className="rounded-full bg-[#d9503f] px-5 py-3 text-sm font-bold text-white disabled:opacity-35" disabled={locked||!!busy} onClick={()=>void artifact("DESIGN_PACK")} type="button">Préparer le dossier complet</button><button className="rounded-full border border-black px-5 py-3 text-sm font-bold disabled:opacity-35" disabled={locked||!!busy||!data.artifacts.includes("DESIGN_PACK")} onClick={()=>void validate()} type="button">Terminer cette étape →</button></div><div className="mt-5"><NextAction>{data.artifacts.includes("DESIGN_PACK")?"Le dossier est prêt : termine cette étape.":!accepted(data.decisions)?"Réponds aux questions puis demande à HORUS de préparer les choix.":"Enregistre, puis prépare le dossier complet."}</NextAction></div></section>;
}
