import { useState } from "react";
import { AnalyzeWorkspace } from "./AnalyzeWorkspace";
import { ModelWorkspace } from "./ModelWorkspace";
import { DesignWorkspace } from "./DesignWorkspace";
import { BuildWorkspace } from "./BuildWorkspace";
import { TestWorkspace } from "./TestWorkspace";
import { DeployWorkspace } from "./DeployWorkspace";
import type { OverviewPhase, Project, ProjectOverview, User } from "./api";

const names:Record<string,string>={ANALYZE:"Comprendre ton idée",MODEL:"Organiser le produit",DESIGN:"Imaginer son fonctionnement",BUILD:"Construire",TEST:"Vérifier",DEPLOY:"Mettre en ligne"};
function progress(phase:OverviewPhase){
 if(phase.phase_type!=="ANALYZE"&&phase.status==="VALIDATED")return 100;
 return phase.required_criteria?Math.round(phase.completed_required_criteria/phase.required_criteria*100):0;
}
export function HorusJourney({overview,user,projects,selectedProjectId,token,onSelectProject,onExit,onRefresh}:{overview:ProjectOverview;user:User|null;projects:Project[];selectedProjectId:string;token:string;onSelectProject:(id:string)=>void;onExit:()=>void;onRefresh:()=>Promise<void>}){
 const [view,setView]=useState<"HOME"|"PROJECT"|"JOURNEY">("HOME");const action=overview.next_action;const phase=overview.phases.find(item=>item.id===action?.phase_id)??overview.phases.find(item=>item.status==="IN_PROGRESS"||item.status==="AVAILABLE");const total=Math.round(overview.phases.reduce((sum,item)=>sum+progress(item),0)/6);
 const workspace=phase&&action?<div className="mx-auto max-w-4xl animate-[fadeIn_.35s_ease-out]">{phase.phase_type==="ANALYZE"&&<AnalyzeWorkspace initialStep={action.step} onChanged={onRefresh} phase={phase} projectDescription={overview.project.description??""} projectName={overview.project.name} token={token}/>} {phase.phase_type==="MODEL"&&<ModelWorkspace initialStep={action.step} onChanged={onRefresh} phase={phase} projectName={overview.project.name} token={token}/>} {phase.phase_type==="DESIGN"&&<DesignWorkspace onChanged={onRefresh} phase={phase} token={token}/>} {phase.phase_type==="BUILD"&&<BuildWorkspace onChanged={onRefresh} phase={phase} token={token}/>} {phase.phase_type==="TEST"&&<TestWorkspace onChanged={onRefresh} phase={phase} token={token}/>} {phase.phase_type==="DEPLOY"&&<DeployWorkspace onChanged={onRefresh} phase={phase} token={token}/>}</div>:<div className="py-32 text-center"><h2 className="text-4xl font-semibold">Ton projet est livré. ✓</h2><p className="mt-3 text-black/50">HORUS a accompagné le projet jusqu’à 100 %.</p></div>;
 return <main className="min-h-screen bg-[#f6f1e8] text-[#171714]"><header className="sticky top-0 z-20 border-b border-black/[.06] bg-[#f6f1e8]/90 px-5 py-4 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between"><button className="text-sm font-bold tracking-[.18em]" onClick={()=>setView("HOME")}>HORUS</button><nav className="flex gap-1 rounded-full bg-black/[.04] p-1 text-xs"><button className={`rounded-full px-4 py-2 ${view==="HOME"?"bg-white shadow-sm":""}`} onClick={()=>setView("HOME")}>Accueil</button><button className={`rounded-full px-4 py-2 ${view==="PROJECT"?"bg-white shadow-sm":""}`} onClick={()=>setView("PROJECT")}>Projet</button><button className={`rounded-full px-4 py-2 ${view==="JOURNEY"?"bg-black text-white":""}`} onClick={()=>setView("JOURNEY")}>Journey</button></nav><button className="text-xs text-black/50" onClick={onExit}>{user?.display_name??user?.email??"Quitter"}</button></div></header>
 {view==="HOME"&&<section className="mx-auto max-w-6xl px-5 py-16 sm:py-24"><p className="text-xs uppercase tracking-[.2em] text-[#d9503f]">Bonjour{user?.display_name?` ${user.display_name}`:""}</p><h1 className="mt-4 max-w-3xl text-5xl font-semibold tracking-[-.055em] sm:text-7xl">Reprends ton idée là où tu l’as laissée.</h1><div className="mt-14 grid gap-4 md:grid-cols-2">{projects.map(project=><article className={`rounded-[2rem] border p-7 transition hover:-translate-y-1 ${project.id===selectedProjectId?"border-black/10 bg-white/70":"border-black/[.06]"}`} key={project.id}><button className="w-full text-left" onClick={()=>onSelectProject(project.id)}><p className="text-3xl font-semibold">{project.name}</p><p className="mt-2 text-sm text-black/45">{project.id===selectedProjectId?`${total} % terminé · ${action?.title??"Projet livré"}`:"Ouvrir ce projet"}</p></button>{project.id===selectedProjectId&&<button className="mt-8 rounded-full bg-[#d9503f] px-6 py-3 text-sm font-bold text-white" onClick={()=>setView("JOURNEY")}>Continuer {project.name} →</button>}</article>)}</div></section>}
 {view==="PROJECT"&&<section className="mx-auto max-w-6xl px-5 py-16"><p className="text-xs uppercase tracking-[.2em] text-black/40">Projet</p><div className="mt-3 flex flex-wrap items-end justify-between gap-6"><div><h1 className="text-6xl font-semibold tracking-[-.055em]">{overview.project.name}</h1><p className="mt-4 max-w-2xl text-black/50">{overview.project.description}</p></div><button className="rounded-full bg-[#d9503f] px-7 py-4 font-bold text-white" onClick={()=>setView("JOURNEY")}>{action?.cta??"Voir le projet"} →</button></div><div className="mt-14 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{overview.phases.map(item=><article className="rounded-2xl border border-black/[.07] bg-white/45 p-5" key={item.id}><span className="text-xs text-black/35">0{item.position}</span><h2 className="mt-8 text-lg font-semibold">{names[item.phase_type]}</h2><p className="mt-1 text-xs text-black/45">{item.status==="VALIDATED"?"Terminé ✓":item.id===phase?.id?"En cours":"À venir"}</p></article>)}</div>{action&&<article className="mt-8 rounded-[2rem] bg-[#1b1b18] p-7 text-white"><p className="text-xs uppercase tracking-[.18em] text-white/40">Prochaine action</p><h2 className="mt-5 text-2xl font-semibold">{action.title}</h2><p className="mt-2 text-sm text-white/55">{action.reason}</p></article>}</section>}
 {view==="JOURNEY"&&<section className="px-5 pb-24"><div className="mx-auto flex max-w-4xl items-center justify-between pt-7"><button className="text-sm text-black/45" onClick={()=>setView("PROJECT")}>← Vue du projet</button><p className="text-sm"><strong>{overview.project.name}</strong><span className="ml-2 text-black/35">· {total} %</span></p></div>{action&&<div className="mx-auto mt-8 max-w-4xl"><p className="text-xs uppercase tracking-[.18em] text-[#d9503f]">{names[action.phase]}</p><p className="mt-2 text-sm text-black/45">{action.reason}</p></div>}{workspace}</section>}
 </main>
}
