import { useEffect, useState, type FormEvent } from "react";
import { api, type OverviewPhase, type TestWorkspaceData } from "./api";

const empty: TestWorkspaceData = { build_plan_ready:false, requirements:[], tasks:[], test_cases:[], defects:[], progress:{total:0,executed:0,passed:0,failed:0,blocked:0,percent:0,pass_rate:0}, artifacts:[] };
const types = ["UNIT","INTEGRATION","E2E","SECURITY","PERFORMANCE","MANUAL"];

export function TestWorkspace({phase,token,onChanged}:{phase:OverviewPhase;token:string;onChanged:()=>Promise<void>}) {
  const [data,setData]=useState(empty); const [title,setTitle]=useState(""); const [expected,setExpected]=useState(""); const [kind,setKind]=useState("UNIT"); const [requirement,setRequirement]=useState(""); const [busy,setBusy]=useState(""); const [error,setError]=useState("");
  const locked=phase.status==="LOCKED"||phase.status==="VALIDATED";
  useEffect(()=>{let cancelled=false;api.testing(phase.id,token).then(value=>{if(!cancelled){setData(value);setRequirement(value.requirements[0]?.id??"")}}).catch(()=>!cancelled&&setError("Impossible de charger les tests."));return()=>{cancelled=true}},[phase.id,token]);
  async function run(label:string, action:()=>Promise<TestWorkspaceData>){setBusy(label);setError("");try{setData(await action());await onChanged()}catch{setError("Action impossible : vérifiez les prérequis et les résultats.")}finally{setBusy("")}}
  async function addCase(event:FormEvent){event.preventDefault();await run("case",()=>api.createTestCase(phase.id,{requirement_id:requirement,title,test_type:kind,expected_result:expected},token));setTitle("");setExpected("")}
  async function report(){setBusy("report");setError("");try{await api.generateTestReport(phase.id,token);setData(await api.testing(phase.id,token));await onChanged()}catch{setError("Tous les tests doivent réussir et aucun défaut bloquant ne doit rester ouvert.")}finally{setBusy("")}}
  return <section className="mt-14 rounded-[2rem] border border-black/10 bg-white/55 p-6 sm:p-8" id="test-workspace">
    <p className="text-xs font-semibold uppercase tracking-[.2em] text-[#d9503f]">Phase 05 · Tester</p>
    <div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-4xl font-semibold">Prouver avant de déployer.</h2><p className="mt-2 text-sm text-black/50">Cas traçables, résultats mesurés et anomalies explicites.</p></div><div className="rounded-2xl bg-black p-4 text-white"><p className="text-xs text-white/50">Exécution · réussite</p><p className="text-2xl font-semibold">{data.progress.percent}% · {data.progress.pass_rate}%</p></div></div>
    {!data.build_plan_ready&&<p className="mt-5 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Un Build Plan validé est requis.</p>}
    <div className="mt-8 grid gap-5 lg:grid-cols-[.75fr_1.25fr]">
      <form className="rounded-2xl border border-black/10 p-5" onSubmit={e=>void addCase(e)}><h3 className="font-semibold">Nouveau cas de test</h3><div className="mt-4 grid gap-2"><input className="rounded-lg border p-2 text-sm" disabled={locked} onChange={e=>setTitle(e.target.value)} placeholder="Scénario" required value={title}/><select className="rounded-lg border p-2 text-sm" disabled={locked} onChange={e=>setKind(e.target.value)} value={kind}>{types.map(x=><option key={x}>{x}</option>)}</select><select className="rounded-lg border p-2 text-sm" disabled={locked} onChange={e=>setRequirement(e.target.value)} required value={requirement}><option value="">Exigence liée…</option>{data.requirements.map(x=><option key={x.id} value={x.id}>{x.code} — {x.title}</option>)}</select><textarea className="rounded-lg border p-2 text-sm" disabled={locked} onChange={e=>setExpected(e.target.value)} placeholder="Résultat attendu" required value={expected}/><button className="rounded-lg bg-black px-4 py-2 text-sm font-bold text-white disabled:opacity-40" disabled={locked||!!busy}>Ajouter</button></div></form>
      <article className="rounded-2xl border border-black/10 p-5"><h3 className="font-semibold">Campagne de test</h3><div className="mt-4 space-y-2">{data.test_cases.map(test=><div className="rounded-xl bg-black/[.035] p-3" key={test.id}><div className="flex items-center gap-3"><div className="min-w-0 flex-1"><p className="text-xs text-black/40">{test.code} · {test.test_type}</p><p className="font-semibold">{test.title}</p></div><select aria-label={`Résultat ${test.code}`} className="rounded-lg border p-2 text-xs" disabled={locked||!!busy} onChange={e=>void run("result",()=>api.executeTestCase(phase.id,test.id,e.target.value,e.target.value==="PASSED"?"Conforme":e.target.value,token))} value={test.status}>{["NOT_RUN","PASSED","FAILED","BLOCKED"].map(x=><option key={x}>{x}</option>)}</select></div>{(test.status==="FAILED"||test.status==="BLOCKED")&&<button className="mt-2 text-xs font-semibold text-[#d9503f]" disabled={locked||!!busy} onClick={()=>void run("defect",()=>api.createTestDefect(phase.id,{test_case_id:test.id,title:`Anomalie ${test.code}`,description:test.actual_result??"Résultat non conforme",severity:test.status==="BLOCKED"?"BLOCKING":"NON_BLOCKING"},token))}>Créer une anomalie</button>}</div>)}</div></article>
    </div>
    <article className="mt-5 rounded-2xl border border-black/10 p-5"><h3 className="font-semibold">Anomalies</h3><div className="mt-3 flex flex-wrap gap-2">{data.defects.map(defect=><span className={`rounded-full border px-3 py-2 text-xs ${defect.severity==="BLOCKING"&&defect.status==="OPEN"?"border-red-400 bg-red-50":""}`} key={defect.id}>{defect.title} · {defect.severity} · {defect.status}{defect.status==="OPEN"&&<button className="ml-2 underline" disabled={locked||!!busy} onClick={()=>void run("resolve",()=>api.resolveTestDefect(phase.id,defect.id,"Corrigée et vérifiée",token))}>Résoudre</button>}</span>)}</div></article>
    {error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <div className="mt-6 flex gap-3"><button className="rounded-full bg-[#d9503f] px-5 py-2 text-sm font-bold text-white disabled:opacity-35" disabled={locked||!!busy} onClick={()=>void report()}>{data.artifacts.includes("TEST_REPORT")?"✓ Régénérer le rapport":"Générer TEST_REPORT"}</button><button className="rounded-full border border-black px-5 py-2 text-sm font-bold disabled:opacity-35" disabled={locked||!!busy||!data.artifacts.includes("TEST_REPORT")} onClick={()=>void api.validatePhase(phase.id,token,"Rapport de test validé").then(onChanged).catch(()=>setError("Le rapport de test doit être prêt."))}>{phase.status==="VALIDATED"?"Phase validée":"Valider Tester →"}</button></div>
  </section>
}
