import { useEffect,useState,type FormEvent } from "react";
import { api,type OverviewPhase,type TestWorkspaceData } from "./api";
import { AdvancedSection,GuidedQuestion,NextAction } from "./GuidedUx";
const empty:TestWorkspaceData={build_plan_ready:false,requirements:[],tasks:[],test_cases:[],defects:[],progress:{total:0,executed:0,passed:0,failed:0,blocked:0,percent:0,pass_rate:0},artifacts:[]};
const resultLabels:Record<string,string>={NOT_RUN:"Pas encore testé",PASSED:"Ça fonctionne",FAILED:"Ça ne fonctionne pas",BLOCKED:"Impossible à tester"};
export function TestWorkspace({phase,token,onChanged}:{phase:OverviewPhase;token:string;onChanged:()=>Promise<void>}){
 const [data,setData]=useState(empty);const [action,setAction]=useState("");const [expected,setExpected]=useState("");const [requirement,setRequirement]=useState("");const [busy,setBusy]=useState("");const [error,setError]=useState("");const locked=phase.status==="LOCKED"||phase.status==="VALIDATED";
 useEffect(()=>{let stop=false;api.testing(phase.id,token).then(value=>{if(!stop){setData(value);setRequirement(value.requirements[0]?.id??"")}}).catch(()=>!stop&&setError("Impossible de charger les vérifications."));return()=>{stop=true}},[phase.id,token]);
 async function run(label:string,fn:()=>Promise<TestWorkspaceData>){setBusy(label);setError("");try{setData(await fn());await onChanged()}catch{setError("Cette action n’est pas possible pour le moment. Consulte la prochaine étape.")}finally{setBusy("")}}
 async function add(event:FormEvent){event.preventDefault();await run("case",()=>api.createTestCase(phase.id,{requirement_id:requirement,title:action,test_type:"E2E",expected_result:expected},token));setAction("");setExpected("")}
 async function report(){setBusy("report");setError("");try{await api.generateTestReport(phase.id,token);setData(await api.testing(phase.id,token));await onChanged()}catch{setError("Le rapport attend que toutes les vérifications réussissent et qu’aucun problème bloquant ne reste ouvert.")}finally{setBusy("")}}
 const openBlocking=data.defects.filter(item=>item.severity==="BLOCKING"&&item.status==="OPEN").length;const missing=!data.build_plan_ready?"Termine d’abord la construction du produit.":data.test_cases.length===0?"Ajoute un premier scénario à vérifier.":data.progress.executed<data.progress.total?"Indique le résultat de chaque scénario.":data.progress.passed<data.progress.total?"Corrige les scénarios qui ne fonctionnent pas.":openBlocking?`Résous ${openBlocking} problème bloquant.`:!data.artifacts.includes("TEST_REPORT")?"Demande à HORUS de préparer le rapport de vérification.":"Le rapport est prêt : termine cette étape.";
 return <section className="mt-14 rounded-[2rem] border border-black/10 bg-white/55 p-6 sm:p-8" id="test-workspace"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#d9503f]">Phase 05 · Vérifier</p><h2 className="mt-3 text-4xl font-semibold">Vérifions que ton produit fonctionne comme prévu.</h2><p className="mt-2 text-sm text-black/50">Décris une action réelle et ce qui devrait se passer. HORUS organise les vérifications techniques.</p><div className="mt-5 flex items-center gap-3"><div className="h-2 flex-1 rounded-full bg-black/10"><div className="h-full rounded-full bg-[#d9503f]" style={{width:`${data.progress.percent}%`}}/></div><span className="text-sm font-semibold">{data.progress.percent}% vérifié · {data.progress.pass_rate}% réussi</span></div>{!data.build_plan_ready&&<p className="mt-5 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">HORUS attend que la construction soit terminée.</p>}<div className="mt-8 space-y-5">
 <GuidedQuestion complete={data.test_cases.length>0} help="Choisis une fonctionnalité existante, puis écris une phrase simple." example="Action : un utilisateur crée un projet. Résultat attendu : le projet apparaît dans son tableau de bord." number={1} title="Que veux-tu vérifier ?"><form className="grid gap-3" onSubmit={e=>void add(e)}><select aria-label="Fonctionnalité à vérifier" className="rounded-xl border p-3" disabled={locked} onChange={e=>setRequirement(e.target.value)} required value={requirement}><option value="">Choisir une fonctionnalité…</option>{data.requirements.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select><input aria-label="Action" className="rounded-xl border p-3" disabled={locked} onChange={e=>setAction(e.target.value)} placeholder="Action — Un utilisateur…" required value={action}/><textarea aria-label="Résultat attendu" className="rounded-xl border p-3" disabled={locked} onChange={e=>setExpected(e.target.value)} placeholder="Résultat attendu — Le produit…" required value={expected}/><button className="rounded-xl bg-black px-4 py-3 text-sm font-bold text-white disabled:opacity-35" disabled={locked||!!busy}>Ajouter ce scénario</button></form></GuidedQuestion>
 <GuidedQuestion complete={data.progress.total>0&&data.progress.executed===data.progress.total} help="Essaie chaque action et choisis simplement ce que tu observes." number={2} title="Quel résultat observes-tu ?"><div className="space-y-3">{data.test_cases.map(test=><article className="rounded-2xl bg-black/[.035] p-4" key={test.id}><p className="font-semibold">{test.title}</p><p className="mt-1 text-sm text-black/50">Attendu : {test.expected_result}</p><select aria-label={`Résultat de ${test.title}`} className="mt-3 w-full rounded-xl border p-3" disabled={locked||!!busy} onChange={e=>void run("result",()=>api.executeTestCase(phase.id,test.id,e.target.value,e.target.value==="PASSED"?"Conforme":resultLabels[e.target.value],token))} value={test.status}>{Object.entries(resultLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{(test.status==="FAILED"||test.status==="BLOCKED")&&<div className="mt-3 rounded-xl bg-red-50 p-3"><p className="text-sm font-semibold">Quel problème as-tu rencontré ?</p><p className="text-xs text-black/50">{test.status==="BLOCKED"?"Ce problème bloque l’utilisation.":"Ce problème est gênant mais non bloquant."}</p><button className="mt-2 text-sm underline" disabled={locked||!!busy} onClick={()=>void run("defect",()=>api.createTestDefect(phase.id,{test_case_id:test.id,title:`Problème pendant : ${test.title}`,description:test.actual_result??"Résultat différent de celui attendu",severity:test.status==="BLOCKED"?"BLOCKING":"NON_BLOCKING"},token))} type="button">Noter ce problème</button></div>}<AdvancedSection><p className="text-xs">Type suggéré automatiquement : {test.test_type}. Référence : {test.code}.</p></AdvancedSection></article>)}</div></GuidedQuestion>
 <GuidedQuestion complete={openBlocking===0} help="Un problème qui bloque l’utilisation doit être corrigé. Un problème gênant peut être suivi sans bloquer la suite." number={3} title="Les problèmes rencontrés sont-ils résolus ?"><div className="space-y-2">{data.defects.map(defect=><div className={`rounded-xl border p-3 text-sm ${defect.severity==="BLOCKING"&&defect.status==="OPEN"?"border-red-300 bg-red-50":""}`} key={defect.id}><strong>{defect.title}</strong><span className="ml-2 text-xs">{defect.severity==="BLOCKING"?"Bloque l’utilisation":"Gênant mais non bloquant"} · {defect.status==="OPEN"?"À traiter":"Traité"}</span>{defect.status==="OPEN"&&<button className="ml-3 underline" disabled={locked||!!busy} onClick={()=>void run("resolve",()=>api.resolveTestDefect(phase.id,defect.id,"Corrigé et vérifié",token))} type="button">Marquer comme résolu</button>}</div>)}</div></GuidedQuestion>
 </div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 flex flex-wrap gap-3"><button className="rounded-full bg-[#d9503f] px-5 py-3 text-sm font-bold text-white disabled:opacity-35" disabled={locked||!!busy} onClick={()=>void report()} type="button">{data.artifacts.includes("TEST_REPORT")?"✓ Mettre à jour le rapport":"Préparer le rapport de vérification"}</button><button className="rounded-full border border-black px-5 py-3 text-sm font-bold disabled:opacity-35" disabled={locked||!!busy||!data.artifacts.includes("TEST_REPORT")} onClick={()=>void api.validatePhase(phase.id,token,"Vérifications terminées").then(onChanged).catch(()=>setError("Le rapport doit être prêt et refléter les résultats actuels."))} type="button">Terminer cette étape →</button></div><div className="mt-5"><NextAction>{missing}</NextAction></div></section>;
}
